// ==========================================
// VRAGENLIJST (255 VRAGEN)
// ==========================================

const VRAGEN = [
  // === KENNIS VRAGEN (76 stuks) ===
  { id: 1, type: "Kennis", difficulty: "medium", text: "Hoe heet het paard van Sinterklaas?", answer: "Ozosnel (vroeger Amerigo)" },
  { id: 2, type: "Kennis", difficulty: "medium", text: "Wat leg je in de schoen voor het paard van Sint?", answer: "Een wortel, water of hooi." },
  { id: 3, type: "Kennis", difficulty: "medium", text: "Wat heeft Sinterklaas op zijn hoofd?", answer: "Een mijter, die rood is met een goudkleurig kruis." },
  { id: 4, type: "Kennis", difficulty: "medium", text: "Wat is een tabberd?", answer: "De naam van Sinterklaas' lange rode mantel." },
  { id: 5, type: "Kennis", difficulty: "medium", text: "Wat heeft Sinterklaas onder zijn rode mantel?", answer: "Een lange witte jurk (albe) of andere kleding van een bisschop." },
  { id: 6, type: "Kennis", difficulty: "medium", text: "Waarom heeft Sinterklaas een baard?", answer: "Omdat hij heel oud is." },
  { id: 7, type: "Kennis", difficulty: "medium", text: "Welke kleur hebben de handschoenen die Sinterklaas meestal heeft?", answer: "Wit." },
  { id: 8, type: "Kennis", difficulty: "medium", text: "Waarvan is de naam Sinterklaas afgeleid?", answer: "Een verbastering van Sint Nicolaas." },
  { id: 9, type: "Kennis", difficulty: "medium", text: "In welke maand komt Sinterklaas meestal met de boot aan in Nederland?", answer: "In november." },
  { id: 10, type: "Kennis", difficulty: "medium", text: "Welk vervoermiddel gebruikt Sinterklaas voor de intocht?", answer: "Een stoomboot." },
  { id: 11, type: "Kennis", difficulty: "medium", text: "Wat komt er uit de schoorsteen van de stoomboot?", answer: "Rook of stoom." },
  { id: 12, type: "Kennis", difficulty: "medium", text: "Wat is de datum van Sinterklaasavond (Pakjesavond)?", answer: "5 december." },
  { id: 13, type: "Kennis", difficulty: "medium", text: "Wat is de dag dat Sinterklaas officieel vertrekt?", answer: "6 december." },
  { id: 14, type: "Kennis", difficulty: "medium", text: "In welk seizoen vindt het Sinterklaasfeest plaats?", answer: "De herfst (en begin van de winter)." },
  { id: 15, type: "Kennis", difficulty: "medium", text: "Wat moet je meestal doen voordat je je Sinterklaascadeau open mag maken?", answer: "Eerst het gedicht (voor)lezen." },
  { id: 16, type: "Kennis", difficulty: "medium", text: "Wie schrijft de gedichten en rijmpjes bij de pakjes?", answer: "De Rijmpiet." },
  { id: 17, type: "Kennis", difficulty: "medium", text: "Hoe heet de grappige, creatieve verpakking die je rond een cadeautje maakt voor Pakjesavond?", answer: "Surprise" },
  { id: 18, type: "Kennis", difficulty: "medium", text: "Hoe heet het boek waarin Sinterklaas alle namen van kinderen opschrijft?", answer: "Het Grote Boek." },
  { id: 19, type: "Kennis", difficulty: "medium", text: "Wat is het verschil tussen kruidnoten en pepernoten?", answer: "Kruidnoten zijn de kleine, harde, ronde kruidige koekjes; pepernoten zijn zachtere, onregelmatige blokjes van taaier deeg." },
  { id: 20, type: "Kennis", difficulty: "medium", text: "Wat zijn de belangrijkste ingrediënten van marsepein?", answer: "Amandelen en suiker." },
  { id: 21, type: "Kennis", difficulty: "medium", text: "Wat zit er in een banketstaaf?", answer: "Amandelspijs (in bladerdeeg)." },
  { id: 22, type: "Kennis", difficulty: "medium", text: "Waardoor wordt speculaas zo lekker en bruin?", answer: "Door Speculaaskruiden." },
  { id: 23, type: "Kennis", difficulty: "medium", text: "Welke soorten chocoladeletters (smaak) bestaan er meestal?", answer: "Melkchocolade, pure chocolade en witte chocolade." },
  { id: 24, type: "Kennis", difficulty: "medium", text: "Welke letter van de chocoladeletter krijg je meestal?", answer: "De eerste letter van je naam." },
  { id: 25, type: "Kennis", difficulty: "medium", text: "Welk rond oranje fruit krijg je vaak in je schoen naast snoep?", answer: "Een mandarijn of sinaasappel." },
  { id: 26, type: "Kennis", difficulty: "medium", text: "Hoe heet het tv-programma dat over Sinterklaas gaat?", answer: "Het Sinterklaasjournaal." },
  { id: 27, type: "Kennis", difficulty: "medium", text: "In welk land woont Sinterklaas als hij niet in Nederland is?", answer: "Spanje." },
  { id: 28, type: "Kennis", difficulty: "medium", text: "Wat houdt Sinterklaas meestal in zijn hand?", answer: "Een gouden staf." },
  { id: 29, type: "Kennis", difficulty: "medium", text: "Wat is het beroep van Sinterklaas?", answer: "Bisschop." },
  { id: 30, type: "Kennis", difficulty: "medium", text: "Waar stoppen de Pieten de cadeautjes in?", answer: "In een (juten) zak." },
  { id: 31, type: "Kennis", difficulty: "medium", text: "Wat dragen Pieten vaak op hun hoofd?", answer: "Een baret met een veer." },
  { id: 32, type: "Kennis", difficulty: "medium", text: "Welke zachte, zoete snoepjes horen bij het strooigoed?", answer: "Schuimpjes." },
  { id: 33, type: "Kennis", difficulty: "medium", text: "Wat is taaitaai?", answer: "Een taaie koek (vaak in de vorm van een pop)." },
  { id: 34, type: "Kennis", difficulty: "medium", text: "Wie heet Sinterklaas altijd welkom bij de intocht in de stad?", answer: "De burgemeester." },
  { id: 35, type: "Kennis", difficulty: "medium", text: "Wat maken kinderen vaak voor Sinterklaas om in de schoen te doen?", answer: "Een tekening (of verlanglijstje)." },
  { id: 36, type: "Kennis", difficulty: "medium", text: "Wat draagt Sinterklaas aan zijn ringvinger?", answer: "Een gouden ring (met een steen)." },
  { id: 37, type: "Kennis", difficulty: "medium", text: "Hoe noemen we de feestelijke aankomst van Sinterklaas in Nederland?", answer: "De intocht." },
  { id: 38, type: "Kennis", difficulty: "medium", text: "Welk \"geld\" krijg je vaak met Sinterklaas?", answer: "Chocolademunten." },
  { id: 39, type: "Kennis", difficulty: "medium", text: "Wat dragen Pieten vaak om hun nek?", answer: "Een (witte) geplooide kraag." },
  { id: 40, type: "Kennis", difficulty: "medium", text: "Hoe heet de bundel takken die Pieten vroeger bij zich droegen?", answer: "De roe." },
  { id: 41, type: "Kennis", difficulty: "medium", text: "Welke koek (in de vorm van een mens) was vroeger een manier om iemand de liefde te verklaren?", answer: "Een speculaaspop (of vrijer)." },
  { id: 42, type: "Kennis", difficulty: "medium", text: "Wat gebeurt er volgens de oude liedjes met stoute kinderen?", answer: "Die moeten mee in de zak (naar Spanje)." },
  { id: 43, type: "Kennis", difficulty: "medium", text: "Welke chocoladeletter wordt in Nederland het meest verkocht?", answer: "De letter M." },
  { id: 44, type: "Kennis", difficulty: "medium", text: "Waarvan is het 'strooien' met snoepgoed oorspronkelijk een symbool?", answer: "Van het zaaien (vruchtbaarheid) op het land." },
  { id: 45, type: "Kennis", difficulty: "medium", text: "Hoeveel punten heeft de mijter van Sinterklaas?", answer: "Twee." },
  { id: 46, type: "Kennis", difficulty: "medium", text: "Wat betekent het woord 'kapoentje' (uit Sinterklaas kapoentje) waarschijnlijk?", answer: "Een deugniet (of haantje)." },
  { id: 47, type: "Kennis", difficulty: "medium", text: "Welke dieren zie je vaak als snoepgoed van chocolade met een vulling van fondant?", answer: "Kikkers en muizen." },
  { id: 48, type: "Kennis", difficulty: "medium", text: "Van welke bekende Nederlandse stad is Sint Nicolaas de beschermheilige?", answer: "Amsterdam." },
  { id: 49, type: "Kennis", difficulty: "medium", text: "Hoe zorgen ze ervoor dat alle chocoladeletters hetzelfde gewicht hebben, ook de 'kleine' letter I?", answer: "De dikte wordt aangepast (of de letter wordt breder gemaakt)." },
  { id: 50, type: "Kennis", difficulty: "medium", text: "Met welk bijzonder vervoermiddel kwam Sinterklaas in 1961 een keer aan in Amsterdam?", answer: "Met een helikopter (of vliegtuig)." },
  { id: 51, type: "Kennis", difficulty: "medium", text: "Wat vond je vroeger in je schoen als teken dat je 'te oud' was geworden voor het feest?", answer: "Een zakje zout." },
  { id: 52, type: "Kennis", difficulty: "medium", text: "Sinterklaas is de beschermheilige van kinderen, maar van welke beroepsgroep nog meer?", answer: "Van zeelieden (schippers)." },
  { id: 53, type: "Kennis", difficulty: "medium", text: "Waarom eten we chocolademunten (naar welke legende verwijzen ze)?", answer: "Sint Nicolaas gooide vroeger zakjes goud door het raam bij drie arme meisjes." },
  { id: 54, type: "Kennis", difficulty: "medium", text: "Wat is waarschijnlijk het oudste Sinterklaasliedje dat we nu nog steeds zingen?", answer: "Zie de maan schijnt door de bomen." },
  { id: 55, type: "Kennis", difficulty: "medium", text: "Welke presentatrice was erbij toen de intocht in 1952 voor het eerst op tv kwam?", answer: "Mies Bouwman." },
  { id: 56, type: "Kennis", difficulty: "medium", text: "Welk kruid is onmisbaar voor de specifieke smaak van taaitaai en 'echte' pepernoten?", answer: "Anijs." },
  { id: 57, type: "Kennis", difficulty: "medium", text: "Hoeveel Pieten had Sinterklaas vroeger (rond 1900) meestal bij zich?", answer: "Maar één (of twee)." },
  { id: 58, type: "Kennis", difficulty: "medium", text: "Waarom zijn varkentjes van marsepein een traditie?", answer: "Het varken was vroeger een symbool voor geluk en welvaart." },
  { id: 59, type: "Kennis", difficulty: "medium", text: "In welk buurland krijgen kinderen de cadeautjes meestal op de ochtend van 6 december?", answer: "België." },
  { id: 60, type: "Kennis", difficulty: "medium", text: "Waar logeren Sinterklaas en de Pieten meestal als ze in Nederland zijn (volgens het Sinterklaasjournaal)?", answer: "In het (Grote) Pietenhuis." },
  { id: 61, type: "Kennis", difficulty: "medium", text: "Maak de zin af: 'Sinterklaasje, bonne, bonne, bonne...'", answer: "'...gooi wat in mijn lege, lege ton.'" },
  { id: 62, type: "Kennis", difficulty: "medium", text: "Welk nummer staat er groot op de Pakjesboot?", answer: "12." },
  { id: 63, type: "Kennis", difficulty: "medium", text: "Hoe heet de vorige presentatrice van het Sinterklaasjournaal?", answer: "Dieuwertje (Blok)." },
  { id: 64, type: "Kennis", difficulty: "medium", text: "Wat is het verschil tussen een Nederlandse en Belgische mijter?", answer: "Op de Nederlandse staat een kruis." },
  { id: 65, type: "Kennis", difficulty: "medium", text: "Maak de zin af: 'O, kom er eens kijken...'", answer: "'...wat ik in mijn schoentje vind.'" },
  { id: 66, type: "Kennis", difficulty: "medium", text: "Waar luisteren Pieten aan om te horen of je slaapt?", answer: "De schoorsteen of het raam." },
  { id: 67, type: "Kennis", difficulty: "medium", text: "Wat betekent het als de wortel de volgende dag nog in je schoen zit?", answer: "Het paard had geen honger (of Sint is het vergeten)." },
  { id: 68, type: "Kennis", difficulty: "medium", text: "Maak de zin af: 'Hoor wie klopt daar kinderen...'", answer: "'...hoor wie klopt daar zachtjes tegen het raam.'" },
  { id: 69, type: "Kennis", difficulty: "medium", text: "Wat betekent het als de vlag op de pakjesboot in top hangt?", answer: "Dat Sinterklaas aan boord is." },
  { id: 70, type: "Kennis", difficulty: "medium", text: "Wat is een surprise?", answer: "Een grappige, creatieve, zelfgemaakte verpakking om een cadeautje heen." },
  { id: 71, type: "Kennis", difficulty: "medium", text: "Wat is 'strooigoed'?", answer: "Snoep om mee te strooien." },
  { id: 72, type: "Kennis", difficulty: "medium", text: "Wat is groter: een mandarijn of een sinaasappel?", answer: "Een sinaasappel." },
  { id: 73, type: "Kennis", difficulty: "medium", text: "Wat betekent 'Sinterklaas kapoentje'?", answer: "Sinterklaas deugniet (liefkozend)." },
  { id: 74, type: "Kennis", difficulty: "medium", text: "Welke kleur is de mantel van Sinterklaas?", answer: "Rood." },
  { id: 75, type: "Kennis", difficulty: "medium", text: "Wat stop je in je schoen?", answer: "Wortel, hooi, tekening." },
  { id: 76, type: "Kennis", difficulty: "medium", text: "Wie is de helper van Sinterklaas?", answer: "Piet." },

  // === ACTIE VRAGEN (50 stuks) ===
  { id: 77, type: "ACTIE", difficulty: "easy", text: "De Pepernoot Lepelloop: Klem een lepel met een pepernoot erop tussen je tanden. Loop een rondje om je stoel en terug.", answer: "Geslaagd als de pepernoot niet valt tijdens het rondje." },
  { id: 78, type: "ACTIE", difficulty: "easy", text: "Piet raakt z'n Neus: Ga op één been staan, doe je ogen dicht en probeer in één keer het puntje van je neus aan te raken.", answer: "Geslaagd als de neus in één keer wordt geraakt zonder balans te verliezen." },
  { id: 79, type: "ACTIE", difficulty: "easy", text: "De Pieten-Gym: Wrijf met je rechterhand rondjes over je buik én tik tegelijk met je linkerhand op je hoofd. Houd dit 10 seconden vol!", answer: "Geslaagd als beide bewegingen 10 seconden tegelijk volgehouden worden.", timeLimit: 10 },
  { id: 80, type: "ACTIE", difficulty: "easy", text: "Het Verboden Woord: De spelleider stelt 3 snelle vragen. Je mag GEEN 'Ja', 'Nee' of 'Euh' zeggen.", answer: "Geslaagd als GEEN 'Ja', 'Nee' of 'Euh' wordt gezegd bij de 3 vragen." },
  { id: 81, type: "ACTIE", difficulty: "easy", text: "Muur-Zit Balans: Ga met je rug tegen de muur en zak tot je benen in een hoek van 90 graden staan. Probeer daarna een pepernoot van de grond te pakken ZONDER je knieën te buigen.", answer: "Geslaagd als de pepernoot van de grond wordt gepakt zonder de knieën te buigen én de 90° hoek vastgehouden wordt." },
  { id: 82, type: "ACTIE", difficulty: "easy", text: "Uitbeelden (Geheim!):\nDe spelleider laat deze opdracht alleen aan jou zien.\n\nBeeld voor de groep uit: 'Een Piet die uitglijdt op het dak'. De groep moet het raden!", answer: "Geslaagd als de groep het correct raadt." },
  { id: 83, type: "ACTIE", difficulty: "easy", text: "Ninja Reflex: De spelleider laat een pepernoot vallen. Vang hem voordat hij de grond raakt!", answer: "Geslaagd als de pepernoot wordt gevangen voordat deze de grond raakt." },
  { id: 84, type: "ACTIE", difficulty: "easy", text: "Snel Rijmen: Rijm binnen 5 tellen op de zin: \"De Sint is weer in het land...\"", answer: "Geslaagd als er binnen 5 tellen een correcte rijm op \"De Sint is weer in het land...\" wordt genoemd.", timeLimit: 5 },
  { id: 85, type: "ACTIE", difficulty: "easy", text: "De Flamingo: Ga op één been staan, doe je ogen dicht en tel hardop terug van 10 naar 0.", answer: "Geslaagd als de speler op één been blijft staan (ogen dicht) tot de 0.", timeLimit: 10 },
  { id: 86, type: "ACTIE", difficulty: "easy", text: "Sint Liedjes Geheugen: Noem binnen 10 seconden 5 verschillende Sinterklaasliedjes. Er mogen geen stiltes vallen!", answer: "Geslaagd als 5 verschillende Sinterklaasliedjes binnen 10 seconden, zonder stiltes, zijn genoemd.", timeLimit: 10 },
  { id: 87, type: "ACTIE", difficulty: "easy", text: "Sprint naar de Deur: Ren naar de voordeur, tik 'm aan en kom zo snel mogelijk terug. (Binnen 10 seconden!)", answer: "Geslaagd als de speler binnen 10 seconden heen en terug is.", timeLimit: 10 },
  { id: 88, type: "ACTIE", difficulty: "easy", text: "Blind Tekenen (Geheim!):\nDe spelleider laat deze opdracht alleen aan jou zien.\n\nTeken een huisje of een mijter terwijl je naar het PLAFOND kijkt.", answer: "Geslaagd als het getekende huisje/mijter herkenbaar is (groep beslist)." },
  { id: 89, type: "ACTIE", difficulty: "easy", text: "Pinguïn Wandelen: Klem een kussen tussen je knieën en waggel naar de deur en terug.", answer: "Geslaagd als het kussen niet valt tijdens het waggelen naar de deur en terug." },
  { id: 90, type: "ACTIE", difficulty: "easy", text: "Staar-Winst: Kijk je buurman of buurvrouw 15 seconden strak aan zonder te lachen. Wie lacht, is af.", answer: "Geslaagd als de speler de buurman 15 seconden aankijkt zonder te lachen.", timeLimit: 15 },
  { id: 91, type: "ACTIE", difficulty: "easy", text: "Blaas-Voetbal: Blaas een propje papier van de ene kant van de tafel naar de overkant (zonder dat het eraf valt!).", answer: "Geslaagd als het propje de overkant van de tafel bereikt zonder eraf te vallen." },
  { id: 92, type: "ACTIE", difficulty: "easy", text: "Toneel Spelen (Geheim!):\nDe spelleider laat deze opdracht alleen aan jou zien.\n\nDoe alsof je een loodzware zak vol cadeaus optilt. Moet geloofwaardig zijn.", answer: "Geslaagd als het 'optillen' geloofwaardig is (groep beslist)." },
  { id: 93, type: "ACTIE", difficulty: "easy", text: "Neuriën Raadsel (Geheim!):\nDe spelleider laat deze opdracht alleen aan jou zien.\n\nNeurie het liedje \"Sinterklaas Kapoentje\" (niet zingen!). De groep moet het raden.", answer: "Geslaagd als de groep het liedje correct raadt." },
  { id: 94, type: "ACTIE", difficulty: "easy", text: "Hand-Toren: Stapel 4 pepernoten op de RUG van je hand. Moet 5 tellen blijven staan.", answer: "Geslaagd als de toren van 4 op de rug van de hand 5 tellen blijft staan.", timeLimit: 5 },
  { id: 95, type: "ACTIE", difficulty: "easy", text: "De Kleuren Jacht: Wijs binnen 10 seconden iets PAARS of GOUDS aan in de kamer.", answer: "Geslaagd als binnen 10 seconden iets PAARS of GOUDS wordt aangewezen.", timeLimit: 10 },
  { id: 96, type: "ACTIE", difficulty: "easy", text: "Reken Maar Uit!: Sint bezoekt 3 kinderen, en elk kind krijgt 2 pakjes. Hoeveel pakjes zijn dat in totaal?", answer: "Antwoord: 6 pakjes." },
  { id: 97, type: "ACTIE", difficulty: "easy", text: "Pepernoot Vangen: Gooi een pepernoot omhoog en vang hem met je mond. Je hebt 3 pogingen.", answer: "Geslaagd als de pepernoot binnen 3 pogingen met de mond wordt gevangen." },
  { id: 98, type: "ACTIE", difficulty: "easy", text: "Toren van Pisa: Bouw een toren van 5 pepernoten op tafel. Je hebt maximaal 15 seconden.", answer: "Geslaagd als de toren van 5 pepernoten binnen 15 seconden blijft staan.", timeLimit: 15 },
  { id: 99, type: "ACTIE", difficulty: "easy", text: "Mikken (met je Rug): Ga met je rug naar een stoel staan. Gooi een propje papier over je schouder, zodat het op de stoel landt.", answer: "Geslaagd als het propje op de stoel landt." },
  { id: 100, type: "ACTIE", difficulty: "easy", text: "Spiegelbeeld Tekenen (Geheim!):\nDe spelleider laat deze opdracht alleen aan jou zien.\n\nTeken een mijter met je 'verkeerde' hand (de hand die je niet gebruikt om te schrijven).", answer: "Geslaagd als het getekende mijter herkenbaar is (groep beslist)." },
  { id: 101, type: "ACTIE", difficulty: "easy", text: "Vingervlug: Raak met je duim razendsnel al je andere vingertoppen aan, heen en weer.", answer: "Geslaagd als alle vingers razendsnel en zonder haperen worden aangeraakt." },
  { id: 102, type: "ACTIE", difficulty: "easy", text: "De Stoomfluit: Doe het geluid van de stoomboot na, zo hard mogelijk! (\"Tuuuuuut!\")", answer: "Geslaagd als het geluid van de boot hard en duidelijk wordt nagebootst." },
  { id: 103, type: "ACTIE", difficulty: "easy", text: "Balanceren: Leg een pepernoot op je neus en houd je hoofd 10 seconden achterover.", answer: "Geslaagd als de pepernoot 10 seconden op de neus blijft liggen.", timeLimit: 10 },
  { id: 104, type: "ACTIE", difficulty: "easy", text: "Ik Ga Op Reis...: Noem 3 dingen die de Sint meeneemt (bijvoorbeeld: staf, mijter, grote boek) snel achter elkaar!", answer: "Geslaagd als 3 Sint-gerelateerde items snel achter elkaar worden genoemd." },
  { id: 105, type: "ACTIE", difficulty: "easy", text: "De Pieten-Wissel: Linkerhand naar je rechteroor, rechterhand naar je neus. Klap in je handen en wissel SNELLER. Herhaal dit 3 keer snel achter elkaar.", answer: "Geslaagd als de wissel 3 keer snel achter elkaar lukt zonder in de knoop te raken." },
  { id: 106, type: "ACTIE", difficulty: "easy", text: "De Cadeau-Draai: Draai 3 keer snel rond in het rond. Wijs direct na het stoppen (met je ogen dicht) de spelleider aan.", answer: "Geslaagd als de speler de spelleider direct aanwijst, terwijl de ogen dicht zijn." },
  { id: 107, type: "ACTIE", difficulty: "easy", text: "Pepernoot-Estafette: Plaats een pepernoot op je voorhoofd en laat deze in je mond glijden zonder je handen te gebruiken. (Je mag je hoofd bewegen.)", answer: "Geslaagd als de pepernoot de mond bereikt." },
  { id: 108, type: "ACTIE", difficulty: "easy", text: "Boek Balans: Balans een pepernoot op je wijsvinger. Tegelijkertijd moet je met je andere hand het Grote Boek (of een ander dik boek) van de Sint boven je hoofd houden (10 seconden).", answer: "Geslaagd als de pepernoot niet valt én het boek niet beweegt.", timeLimit: 10 },
  { id: 109, type: "ACTIE", difficulty: "easy", text: "De Stoomboot (Geheim!):\nDe spelleider laat deze opdracht alleen aan jou zien.\n\nMaak in 5 seconden het geluid én de beweging van een stoomboot die de haven in vaart.", answer: "Geslaagd als de speler in 5 seconden zowel het geluid als de beweging maakt.", timeLimit: 5 },
  { id: 110, type: "ACTIE", difficulty: "easy", text: "Vier Rijmwoorden: Noem binnen 5 seconden vier verschillende rijmwoorden op het woord 'Staf'.", answer: "Antwoord: Maf, straf, laf, waf, etc.", timeLimit: 5 },
  { id: 111, type: "ACTIE", difficulty: "easy", text: "De Zak van Sinterklaas: Piet heeft 25 cadeaus. Hij heeft 3 schoorstenen die hij nog moet doen. Bij de eerste levert hij 7 pakjes af en bij de tweede 8 pakjes. Hoeveel pakjes blijven over voor de derde schoorsteen?", answer: "Antwoord: 25 - 7 - 8 = 10 pakjes." },
  { id: 112, type: "ACTIE", difficulty: "easy", text: "Pepernoot Productie: Een bakker maakt 600 pepernoten. Hij verdeelt deze over 15 zakjes voor de kinderen. Hoeveel pepernoten zitten er in elk zakje?", answer: "Antwoord: 600 / 15 = 40 pepernoten." },
  { id: 113, type: "ACTIE", difficulty: "easy", text: "Schouders: Leg een pepernoot op elke schouder. Ga staan en zit weer zonder dat ze vallen.", answer: "Geslaagd als de pepernoten niet vallen." },
  { id: 114, type: "ACTIE", difficulty: "easy", text: "Galgje: Noem een Sinterklaaswoord van 5 letters dat de letter 'E' niet bevat (bijv. Sint, Staf, Zak).", answer: "Geslaagd als je binnen 5 seconden een correct woord noemt.", timeLimit: 5 },
  { id: 115, type: "ACTIE", difficulty: "easy", text: "Liplezen (Geheim!):\nDe spelleider laat deze opdracht alleen aan jou zien.\n\nZeg geluidloos het woord 'Pepernoten'. De groep moet het raden.", answer: "Geslaagd als de groep het correct raadt." },
  { id: 116, type: "ACTIE", difficulty: "easy", text: "Squats: Doe 5 squats (kniebuigingen) terwijl je een Sinterklaasliedje fluit.", answer: "Geslaagd als je 5 squats maakt zonder te stoppen met fluiten." },
  { id: 117, type: "ACTIE", difficulty: "easy", text: "Balans Schoenzitting: Zet je eigen schoen op je hoofd en loop naar de deur en terug.", answer: "Geslaagd als de schoen niet valt." },
  { id: 118, type: "ACTIE", difficulty: "easy", text: "Tongbreker: Zeg 3x heel snel: 'De knappe kapper knipt knappe koppen'.", answer: "Geslaagd als je de zin 3x snel zegt zonder te struikelen." },
  { id: 119, type: "ACTIE", difficulty: "easy", text: "De Kreeft: Loop achteruit een rondje om de tafel (in gewone loopstand).", answer: "Geslaagd als je een rondje loopt zonder ergens tegenaan te botsen." },
  { id: 120, type: "ACTIE", difficulty: "easy", text: "Reactie Spel: De spelleider zegt afwisselend 'Pepernoot' (klap!) of 'Kruidnoot' (stamp!). De speler moet 5 opdrachten goed doen.", answer: "Geslaagd als 5 opdrachten goed worden uitgevoerd zonder fouten." },
  { id: 121, type: "ACTIE", difficulty: "easy", text: "De Knikker Klem: Houd een pepernoot tussen je kin en je borst geklemd. Zeg vervolgens 'Dank u Sinterklaasje'.", answer: "Geslaagd als de pepernoot niet valt tijdens het praten." },
  { id: 122, type: "ACTIE", difficulty: "easy", text: "Tellen met Sprongen: Tel met sprongen van 2 tot 20 (2, 4, 6...).", answer: "Geslaagd als je binnen 5 seconden foutloos tot 20 telt.", timeLimit: 5 },
  { id: 123, type: "Kennis", difficulty: "medium", text: "Noem binnen 5 seconden 3 namen die met de letter S beginnen.", answer: "Voorbeelden: Sara, Sanne, Steven, Simon, Sophie, Stijn, etc.", timeLimit: 5 },
  { id: 124, type: "ACTIE", difficulty: "easy", text: "De Krab Loop: Loop zijwaarts (als een krab) een rondje om je stoel.", answer: "Geslaagd als je een rondje loopt zonder ergens tegenaan te botsen." },
  { id: 125, type: "ACTIE", difficulty: "easy", text: "Vingers Raden: Steek achter je rug een aantal vingers op (bv. 4). Je linkerbuurman moet raden hoeveel.", answer: "Geslaagd als je buurman het niet raadt (anders verlies je je beurt)." },
  { id: 126, type: "ACTIE", difficulty: "easy", text: "De Staf Balans: Balanceer een pen of potlood (als 'Staf') rechtop op je wijsvinger terwijl je een rondje van 360° draait.", answer: "Geslaagd als de 'Staf' niet valt tijdens de volledige draai.", timeLimit: 5 },

  // === ANDERE VRAAGTYPEN (129 stuks) ===
  // --- 2025 Vragen (11 stuks) ---
  { id: 127, type: "2025", difficulty: "medium", text: "Waar kwam de stoomboot dit jaar (2025) aan?", answer: "Op Texel (Oudeschild)" },
  { id: 128, type: "2025", difficulty: "medium", text: "Wie presenteerde de landelijke intocht dit jaar op tv?", answer: "Merel Westrik" },
  { id: 129, type: "2025", difficulty: "medium", text: "Welke drukke Piet was er na 10 jaar weer bij (gespeeld door Jochem Myjer)?", answer: "Pietje Paniek" },
  { id: 130, type: "2025", difficulty: "medium", text: "Welk dier wees de boot de weg toen de vuurtoren stuk was?", answer: "Een zeehond" },
  { id: 131, type: "2025", difficulty: "medium", text: "Waarom stonden er dit jaar hekken en soldaten om het Pietenhuis?", answer: "Om het te bewaken (het was 'bezet')" },
  { id: 132, type: "2025", difficulty: "medium", text: "De Pieten deelden dit jaar mysterieuze 'Noodpakketten' uit. Wat zat erin?", answer: "Helemaal niets (ze waren leeg)" },
  { id: 133, type: "2025", difficulty: "medium", text: "Voor wie hingen er spandoeken en tekeningen bij de intocht met de tekst \"Dankjewel ...\"?", answer: "Voor Dieuwertje (Blok)" },
  { id: 134, type: "2025", difficulty: "medium", text: "Wie is de nieuwe meneer die de voice-over (de vertelstem) van het Sinterklaasjournaal doet?", answer: "Herman van der Zandt" },
  { id: 135, type: "2025", difficulty: "medium", text: "Welke kleur had de doos van de puzzel (het cadeau voor de burgemeester)?", answer: "Blauw" },
  { id: 136, type: "2025", difficulty: "medium", text: "Wat was er kapot bij Texel waardoor de boot de weg kwijt raakte?", answer: "De lamp van de vuurtoren" },
  { id: 137, type: "2025", difficulty: "medium", text: "Wat zat er per ongeluk tussen de pepernoten (het strooigoed) dit jaar?", answer: "Puzzelstukjes" },

  // --- Lastig Vragen (10 stuks) ---
  { id: 138, type: "Lastig", difficulty: "hard", text: "In welk jaar was de allereerste intocht op de Nederlandse TV?", answer: "1952 (marge van 5 jaar = goed)" },
  { id: 139, type: "Lastig", difficulty: "hard", text: "Wat is de officiële Latijnse naam van Sinterklaas?", answer: "Sanctus Nicolaus" },
  { id: 140, type: "Lastig", difficulty: "hard", text: "Welke stad is de beschermstad van Sint Nicolaas?", answer: "Amsterdam" },
  { id: 141, type: "Lastig", difficulty: "hard", text: "In welke stad is Sinterklaas geboren (niet waar hij bisschop was)?", answer: "Patara (in Turkije)" },
  { id: 142, type: "Lastig", difficulty: "hard", text: "Hoe heet de schrijver die in 1850 bedacht dat de Sint met een stoomboot komt?", answer: "Jan Schenkman" },
  { id: 143, type: "Lastig", difficulty: "hard", text: "Wat is de echte naam van de boot die vaak als 'Pakjesboot 12' wordt gebruikt?", answer: "De Hydrograaf" },
  { id: 144, type: "Lastig", difficulty: "hard", text: "Waarom vieren we Pakjesavond op 5 december en niet op de 6e?", answer: "Omdat we het vieren op de vooravond van zijn verjaardag" },
  { id: 145, type: "Lastig", difficulty: "hard", text: "Welke graansoort wordt gebruikt om échte pepernoten (die taaie brokken) te maken?", answer: "Roggebloem (Rogge)" },
  { id: 146, type: "Lastig", difficulty: "hard", text: "Wat betekenen de drie gouden ballen die je soms op oude plaatjes van de Sint ziet?", answer: "De bruidsschat (geld) die hij aan drie arme meisjes gaf" },
  { id: 147, type: "Lastig", difficulty: "hard", text: "Van welke zachte stof is de rode mantel (tabberd) van Sinterklaas meestal gemaakt?", answer: "Fluweel (of velours)" },

  // --- Expert Vragen (8 stuks) ---
  { id: 148, type: "Expert", difficulty: "hard", text: "In welk jaar werd het kinderboek Sint Nicolaas en zijn knecht (waarin de stoomboot werd geïntroduceerd) geschreven? (Je mag er 25 jaar naast zitten)", answer: "1850 (Alles tussen 1825 en 1875 is goed)" },
  { id: 149, type: "Expert", difficulty: "hard", text: "Sinterklaas wordt vaak afgebeeld met een boek. Wat staat daar (volgens de oude traditie) in, behalve namen van kinderen?", answer: "Het Evangelie (De bijbelteksten)" },
  { id: 150, type: "Expert", difficulty: "hard", text: "Hoe heet de ietwat enge hulp van Sinterklaas in Duitsland?", answer: "Knecht Ruprecht" },
  { id: 151, type: "Expert", difficulty: "hard", text: "Volgens een beroemde legende wekte Sinterklaas drie kinderen weer tot leven. Waar zaten deze kinderen in?", answer: "In een ton met zout (pekelvat)" },
  { id: 152, type: "Expert", difficulty: "hard", text: "Door een legende waarin hij een zware storm tot bedaren bracht, werd Sint Nicolaas de beschermheilige van welke beroepsgroep?", answer: "Zeelieden / Schippers" },
  { id: 153, type: "Expert", difficulty: "hard", text: "Welke letterbanket-letter werd er vroeger traditioneel aan geliefden gegeven als huwelijksaanzoek?", answer: "De letter O (van Oprechtheid, of als ring)" },
  { id: 154, type: "Expert", difficulty: "hard", text: "Er is een theorie dat Sinterklaas elementen heeft overgenomen van een Germaanse god die op een achtbenig paard reed. Welke god?", answer: "Wodan (of Odin)" },
  { id: 155, type: "Expert", difficulty: "hard", text: "Hoe heet de bekende Nederlandse horrorfilm uit 2010 (van Dick Maas) waarin Sinterklaas een kwaadaardig monster is?", answer: "Sint" },

  // --- Instinker Vragen (9 stuks) ---
  { id: 157, type: "Instinker", difficulty: "medium", text: "Sinterklaas rijdt op een schimmel. Wat is een schimmel?", answer: "Een wit paard" },
  { id: 158, type: "Instinker", difficulty: "medium", text: "Wat is zwaarder: Een kilo pepernoten of een kilo schuimpjes?", answer: "Ze zijn even zwaar (Allebei een kilo)" },
  { id: 159, type: "Instinker", difficulty: "medium", text: "Hoe noem je Sinterklaas als hij in de zomer in zijn zwembroek op het strand ligt?", answer: "Sinterklaas" },
  { id: 160, type: "Instinker", difficulty: "medium", text: "Hoeveel letters zitten er in 'Het Grote Boek'? (Timer: 10 sec)", answer: "13 letters (Tel maar na: H-e-t-G-r-o-t-e-B-o-e-k)", timeLimit: 10 },
  { id: 161, type: "Instinker", difficulty: "medium", text: "Wat gaat er wel de schoorsteen in, maar komt er nooit uit?", answer: "Rook" },
  { id: 162, type: "Instinker", difficulty: "medium", text: "Stel: JIJ bent de kapitein van de Pakjesboot. Er zijn 50 Pieten aan boord en 1000 pakjes. Hoe oud is de kapitein?", answer: "Even oud als jij (Want jij bent de kapitein!)" },
  { id: 163, type: "Instinker", difficulty: "medium", text: "Sinterklaas valt van een ladder van 10 meter hoog, maar hij heeft helemaal geen pijn. Hoe kan dat?", answer: "Hij stond op de onderste trede" },
  { id: 164, type: "Instinker", difficulty: "medium", text: "Wat staat er precies in het midden van de 'Pakjesboot'?", answer: "De letter E (Bij het woord 'Pakjesboot')" },
  { id: 165, type: "Instinker", difficulty: "medium", text: "In welke maand eet Sinterklaas de minste pepernoten?", answer: "Februari (Dat is de kortste maand)" },

  // --- Woord hussel Vragen (5 stuks) ---
  { id: 166, type: "Woord hussel", difficulty: "medium", text: "Welk woord kan je maken van: RETMIJ?", answer: "MIJTER", timeLimit: 5 },
  { id: 167, type: "Woord hussel", difficulty: "medium", text: "Welk woord kan je maken van: JASPEN?", answer: "SPANJE", timeLimit: 5 },
  { id: 168, type: "Woord hussel", difficulty: "medium", text: "Welk woord kan je maken van: POORTPEEN?", answer: "PEPERNOOT", timeLimit: 5 },
  { id: 169, type: "Woord hussel", difficulty: "medium", text: "Welk woord kan je maken van: ZONLOSE?", answer: "OZOSNEL", timeLimit: 5 },
  { id: 170, type: "Woord hussel", difficulty: "medium", text: "Welk woord kan je maken van: PIERENMAS?", answer: "MARSEPEIN", timeLimit: 5 },

  // --- Dag Sinterklaasje Vragen (20 stuks) ---
  { id: 171, type: "Dag Sinterklaasje", difficulty: "easy", text: "Hoeveel harten heeft een octopus?", answer: "3" },
  { id: 172, type: "Dag Sinterklaasje", difficulty: "easy", text: "Welk land heeft de vorm van een laars?", answer: "Italië" },
  { id: 173, type: "Dag Sinterklaasje", difficulty: "easy", text: "Is een tomaat groente of fruit?", answer: "Fruit" },
  { id: 174, type: "Dag Sinterklaasje", difficulty: "easy", text: "Hoeveel provincies heeft Nederland?", answer: "12" },
  { id: 175, type: "Dag Sinterklaasje", difficulty: "easy", text: "Wat is het snelste landdier ter wereld?", answer: "Het jachtluipaard (Cheeta)" },
  { id: 176, type: "Dag Sinterklaasje", difficulty: "easy", text: "Wat is het grootste dier ter wereld?", answer: "De Blauwe Vinvis" },
  { id: 177, type: "Dag Sinterklaasje", difficulty: "easy", text: "Wat is de grootste planeet van ons zonnestelsel?", answer: "Jupiter" },
  { id: 178, type: "Dag Sinterklaasje", difficulty: "easy", text: "Kun je niezen met je ogen open?", answer: "Nee (Dat is onmogelijk)" },
  { id: 179, type: "Dag Sinterklaasje", difficulty: "easy", text: "Hoeveel poten heeft een spin?", answer: "8" },
  { id: 180, type: "Dag Sinterklaasje", difficulty: "easy", text: "Wat is het hardste materiaal dat in de natuur voorkomt?", answer: "Diamant" },
  { id: 181, type: "Dag Sinterklaasje", difficulty: "easy", text: "Hoe heet de broer van Super Mario?", answer: "Luigi" },
  { id: 182, type: "Dag Sinterklaasje", difficulty: "easy", text: "Welk dier staat erom bekend dat het van kleur kan veranderen?", answer: "Een Kameleon" },
  { id: 183, type: "Dag Sinterklaasje", difficulty: "easy", text: "Bij hoeveel graden begint water te koken?", answer: "100 graden" },
  { id: 184, type: "Dag Sinterklaasje", difficulty: "easy", text: "Hoe heet de sneeuwpop uit de film Frozen?", answer: "Olaf" },
  { id: 185, type: "Dag Sinterklaasje", difficulty: "easy", text: "Welke taal spreken de mensen in Brazilië?", answer: "Portugees" },
  { id: 186, type: "Dag Sinterklaasje", difficulty: "easy", text: "Hoeveel poten heeft een insect (bijvoorbeeld een mier of vlieg)?", answer: "6 (Spinnen hebben er 8!)" },
  { id: 187, type: "Dag Sinterklaasje", difficulty: "easy", text: "Hoeveel snaren heeft een gitaar meestal?", answer: "6" },
  { id: 188, type: "Dag Sinterklaasje", difficulty: "easy", text: "Welke beroemde tovenaar heeft een bliksemschicht-litteken op zijn voorhoofd?", answer: "Harry Potter" },
  { id: 189, type: "Dag Sinterklaasje", difficulty: "easy", text: "Welke grote vogel steekt (volgens het gezegde) zijn kop in het zand?", answer: "De Struisvogel" },
  { id: 190, type: "Dag Sinterklaasje", difficulty: "easy", text: "Hoeveel dagen heeft een schrikkeljaar?", answer: "366 (Eentje meer dan normaal)" },

  // --- SNELLE JELLE Vragen (10 stuks) ---
  { id: 191, type: "SNELLE JELLE", difficulty: "easy", text: "Noem 3 Sinterklaasliedjes.", answer: "Zie ginds komt de stoomboot, Sinterklaas Kapoentje, De Zak van Sinterklaas...", timeLimit: 5 },
  { id: 192, type: "SNELLE JELLE", difficulty: "easy", text: "Noem 3 dingen die ROOD zijn.", answer: "Brandweerauto, tomaat, aardbei, de mantel van Sint...", timeLimit: 5 },
  { id: 193, type: "SNELLE JELLE", difficulty: "easy", text: "Noem 3 soorten strooigoed (snoep).", answer: "Pepernoten, kruidnoten, schuimpjes, taaitaai, marsepein...", timeLimit: 5 },
  { id: 194, type: "SNELLE JELLE", difficulty: "easy", text: "Noem 3 dingen die je op een pizza doet.", answer: "Kaas, salami, tomatensaus, ananas, ham...", timeLimit: 5 },
  { id: 195, type: "SNELLE JELLE", difficulty: "easy", text: "Noem 3 kledingstukken van Sinterklaas.", answer: "Mijter, mantel, handschoenen, ring, staf (is een accessoire, maar goed rekenen)...", timeLimit: 5 },
  { id: 196, type: "SNELLE JELLE", difficulty: "easy", text: "Noem 3 sporten met een bal.", answer: "Voetbal, tennis, basketbal, volleybal, hockey...", timeLimit: 5 },
  { id: 197, type: "SNELLE JELLE", difficulty: "easy", text: "Noem in 5 seconden 5 apps die je op je telefoon hebt staan.", answer: "WhatsApp, TikTok, Instagram, YouTube, Snapchat, etc. (5 apps noemen)", timeLimit: 5 },
  { id: 198, type: "SNELLE JELLE", difficulty: "easy", text: "Noem 3 dieren die eieren leggen.", answer: "Kip, eend, vogelbekdier, slang, krokodil, pinguïn...", timeLimit: 5 },
  { id: 199, type: "SNELLE JELLE", difficulty: "easy", text: "Noem 3 dingen die in een schooltas zitten.", answer: "Boeken, pennen, lunchtrommel, agenda, etui...", timeLimit: 5 },
  { id: 200, type: "SNELLE JELLE", difficulty: "easy", text: "Noem 3 smaken ijs.", answer: "Vanille, Aardbei, Chocolade, Banaan, Smurfen...", timeLimit: 5 },

  // --- WAAR OF NIET WAAR? Vragen (20 stuks) ---
  { id: 201, type: "WAAR OF NIET WAAR?", difficulty: "easy", text: "Sinterklaas is getrouwd. Is dat waar of niet waar?", answer: "NIET WAAR (Hij is vrijgezel / een bisschop trouwt niet)" },
  { id: 202, type: "WAAR OF NIET WAAR?", difficulty: "easy", text: "Het oog van een struisvogel is groter dan zijn hersenen. Is dat waar of niet waar?", answer: "WAAR" },
  { id: 203, type: "WAAR OF NIET WAAR?", difficulty: "easy", text: "Pepernoten worden gemaakt van oud brood en speculaaskruiden. Is dat waar of niet waar?", answer: "NIET WAAR (Van roggebloem en anijs)" },
  { id: 204, type: "WAAR OF NIET WAAR?", difficulty: "easy", text: "Een slak kan wel 3 jaar achter elkaar slapen. Is dat waar of niet waar?", answer: "WAAR" },
  { id: 205, type: "WAAR OF NIET WAAR?", difficulty: "easy", text: "De Eiffeltoren staat in Londen. Is dat waar of niet waar?", answer: "NIET WAAR (In Parijs)" },
  { id: 206, type: "WAAR OF NIET WAAR?", difficulty: "easy", text: "Pinda's zijn eigenlijk geen noten, maar bonen (peulvruchten). Is dat waar of niet waar?", answer: "WAAR" },
  { id: 207, type: "WAAR OF NIET WAAR?", difficulty: "easy", text: "De staf van Sinterklaas is gemaakt van massief goud. Is dat waar of niet waar?", answer: "NIET WAAR (Dat zou veel te zwaar zijn om te tillen!)" },
  { id: 208, type: "WAAR OF NIET WAAR?", difficulty: "easy", text: "Een goudvis heeft een geheugen van maar 3 seconden. Is dat waar of niet waar?", answer: "NIET WAAR (Dat is een fabeltje, ze onthouden dingen maandenlang)" },
  { id: 209, type: "WAAR OF NIET WAAR?", difficulty: "easy", text: "Varkens kunnen fysiek niet omhoog naar de lucht kijken. Is dat waar of niet waar?", answer: "WAAR (Hun nek is daar niet voor gebouwd)" },
  { id: 210, type: "WAAR OF NIET WAAR?", difficulty: "easy", text: "Sinterklaas is ouder dan de Kerstman. Is dat waar of niet waar?", answer: "WAAR (Sint Nicolaas leefde in de 4e eeuw, de Kerstman is veel later bedacht)" },
  { id: 211, type: "WAAR OF NIET WAAR?", difficulty: "easy", text: "Je oren en je neus blijven je hele leven lang doorgroeien. Is dat waar of niet waar?", answer: "WAAR" },
  { id: 212, type: "WAAR OF NIET WAAR?", difficulty: "easy", text: "Haaien bestonden al voordat er bomen op aarde waren. Is dat waar of niet waar?", answer: "WAAR (Haaien zijn oeroud!)" },
  { id: 213, type: "WAAR OF NIET WAAR?", difficulty: "easy", text: "Je kunt je eigen elleboog likken. Is dat waar of niet waar?", answer: "NIET WAAR (Voor bijna iedereen onmogelijk... probeer maar!)" },
  { id: 214, type: "WAAR OF NIET WAAR?", difficulty: "easy", text: "In Spanje vieren de kinderen ook Pakjesavond op 5 december. Is dat waar of niet waar?", answer: "NIET WAAR (Zij krijgen cadeautjes met Driekoningen op 6 januari)" },
  { id: 215, type: "WAAR OF NIET WAAR?", difficulty: "easy", text: "Witte chocolade is officieel geen chocolade (omdat er geen cacaopoeder in zit). Is dat waar of niet waar?", answer: "WAAR (Er zit wel cacaoboter in, maar geen cacaomassa)" },
  { id: 216, type: "WAAR OF NIET WAAR?", difficulty: "easy", text: "De zon is eigenlijk een ster. Is dat waar of niet waar?", answer: "WAAR" },
  { id: 217, type: "WAAR OF NIET WAAR?", difficulty: "easy", text: "Bliksem slaat nooit twee keer op dezelfde plek in. Is dat waar of niet waar?", answer: "NIET WAAR (Het slaat vaak meerdere keren in op hoge gebouwen)" },
  { id: 218, type: "WAAR OF NIET WAAR?", difficulty: "easy", text: "Een blauwe vinvis heeft een hart zo groot als een auto. Is dat waar of niet waar?", answer: "WAAR" },
  { id: 219, type: "WAAR OF NIET WAAR?", difficulty: "easy", text: "Marsepein wordt gemaakt van gemalen pinda's en suiker. Is dat waar of niet waar?", answer: "NIET WAAR (Van amandelen en suiker)" },
  { id: 220, type: "WAAR OF NIET WAAR?", difficulty: "easy", text: "Mensen en bananen hebben voor ongeveer 50% hetzelfde DNA. Is dat waar of niet waar?", answer: "WAAR" },

  // --- WIE OF WAT BEN IK? Vragen (20 stuks) ---
  { id: 221, type: "WIE OF WAT BEN IK?", difficulty: "medium", text: "Ik ben van goud, ik ben lang en ik heb een mooie krul aan de bovenkant. Wie of wat ben ik?", answer: "De Staf" },
  { id: 222, type: "WIE OF WAT BEN IK?", difficulty: "medium", text: "Ik ben rood, ik sta op een hoofd en er staat een gouden kruis op mij. Wie of wat ben ik?", answer: "De Mijter" },
  { id: 223, type: "WIE OF WAT BEN IK?", difficulty: "medium", text: "Ik ben klein, bruin, knapperig en ik word door de kamer gegooid. Wie of wat ben ik?", answer: "Een Pepernoot (of Kruidnoot)" },
  { id: 224, type: "WIE OF WAT BEN IK?", difficulty: "medium", text: "Ik ben wit, ik heb vier benen en ik loop 's nachts over de daken. Wie of wat ben ik?", answer: "Het Paard (Ozosnel / Amerigo)" },
  { id: 225, type: "WIE OF WAT BEN IK?", difficulty: "medium", text: "Ik ben gemaakt van juten, ik ben loodzwaar en er zitten cadeautjes in. Wie of wat ben ik?", answer: "De Zak (van Sinterklaas)" },
  { id: 226, type: "WIE OF WAT BEN IK?", difficulty: "medium", text: "Ik ben groot, rood en dik. Alle namen van alle kinderen staan in mij geschreven. Wie of wat ben ik?", answer: "Het Grote Boek" },
  { id: 227, type: "WIE OF WAT BEN IK?", difficulty: "medium", text: "Je zet mij bij de haard of de verwarming, maar overdag loop je op mij. Wie of wat ben ik?", answer: "Je Schoen" },
  { id: 228, type: "WIE OF WAT BEN IK?", difficulty: "medium", text: "Ik ben gemaakt van chocolade. Ik ben er in de A, de B, de C... tot de Z! Wie of wat ben ik?", answer: "Een Chocoladeletter" },
  { id: 229, type: "WIE OF WAT BEN IK?", difficulty: "medium", text: "Ik ben een gat in het dak. Ik rook de hele dag, maar ik ben geen sigaret. Wie of wat ben ik?", answer: "De Schoorsteen" },
  { id: 230, type: "WIE OF WAT BEN IK?", difficulty: "medium", text: "Ik kom uit Spanje, ik vaar op het water en ik blaas stoom. Wie of wat ben ik?", answer: "De Stoomboot" },
  { id: 231, type: "WIE OF WAT BEN IK?", difficulty: "medium", text: "Ik ben oranje, gezond en het paard is dol op mij. Wie of wat ben ik?", answer: "Een Wortel" },
  { id: 232, type: "WIE OF WAT BEN IK?", difficulty: "medium", text: "Ik ben een warm land waar sinaasappels groeien en waar de Sint woont. Wie of wat ben ik?", answer: "Spanje" },
  { id: 233, type: "WIE OF WAT BEN IK?", difficulty: "medium", text: "Ik klim, ik klauter, ik maak grappen en ik strooi met snoep. Wie of wat ben ik?", answer: "Piet" },
  { id: 234, type: "WIE OF WAT BEN IK?", difficulty: "medium", text: "Ik ben wit, zoet en vierkant. Het paard snoept mij graag op. Wie of wat ben ik?", answer: "Een Suikerklontje" },
  { id: 235, type: "WIE OF WAT BEN IK?", difficulty: "medium", text: "Ik ben gemaakt van amandelen en suiker en ik ben heel zacht en zoet. Wie of wat ben ik?", answer: "Marsepein" },
  { id: 236, type: "WIE OF WAT BEN IK?", difficulty: "medium", text: "Ik rijm, ik sta op papier en ik word voorgelezen voordat je een pakje openmaakt. Wie of wat ben ik?", answer: "Een Gedicht" },
  { id: 237, type: "WIE OF WAT BEN IK?", difficulty: "medium", text: "Ik ben een geknutseld cadeau waar iets anders in verstopt zit. Wie of wat ben ik?", answer: "Een Surprise" },
  { id: 238, type: "WIE OF WAT BEN IK?", difficulty: "medium", text: "Ik ben rood, lekker warm en ik hang om de schouders van Sinterklaas. Wie of wat ben ik?", answer: "De Mantel (of Tabberd)" },
  { id: 239, type: "WIE OF WAT BEN IK?", difficulty: "medium", text: "Ik heb pannen, maar ik kan niet koken. Het paard loopt over mij heen. Wie of wat ben ik?", answer: "Het Dak" },
  { id: 240, type: "WIE OF WAT BEN IK?", difficulty: "medium", text: "Ik ben de leukste avond van het jaar, meestal op 5 december. Wie of wat ben ik?", answer: "Pakjesavond" },

  // --- SINTERKERSTMAN Vragen (15 stuks) ---
  { id: 241, type: "SINTERKERSTMAN", difficulty: "easy", text: "Wie rijdt er op een wit schimmelpaard? Sinterklaas of de Kerstman?", answer: "Sinterklaas" },
  { id: 242, type: "SINTERKERSTMAN", difficulty: "easy", text: "Wie heeft er vliegende rendieren voor zijn slee? Sinterklaas of de Kerstman?", answer: "De Kerstman" },
  { id: 243, type: "SINTERKERSTMAN", difficulty: "easy", text: "Wie woont er op de Noordpool? Sinterklaas of de Kerstman?", answer: "De Kerstman" },
  { id: 244, type: "SINTERKERSTMAN", difficulty: "easy", text: "Wie woont er in Spanje? Sinterklaas of de Kerstman?", answer: "Sinterklaas" },
  { id: 245, type: "SINTERKERSTMAN", difficulty: "easy", text: "Wie draagt er een mijter (een hoge hoed met een kruis)? Sinterklaas of de Kerstman?", answer: "Sinterklaas" },
  { id: 246, type: "SINTERKERSTMAN", difficulty: "easy", text: "Wie roept er altijd heel hard \"Ho Ho Ho\"? Sinterklaas of de Kerstman?", answer: "De Kerstman" },
  { id: 247, type: "SINTERKERSTMAN", difficulty: "easy", text: "Wie heeft een lange, witte baard? Sinterklaas of de Kerstman?", answer: "Allebei" },
  { id: 248, type: "SINTERKERSTMAN", difficulty: "easy", text: "Wie wordt er geholpen door kleine elfjes? Sinterklaas of de Kerstman?", answer: "De Kerstman" },
  { id: 249, type: "SINTERKERSTMAN", difficulty: "easy", text: "Wie komt er aan met een Stoomboot? Sinterklaas of de Kerstman?", answer: "Sinterklaas" },
  { id: 250, type: "SINTERKERSTMAN", difficulty: "easy", text: "Wie stopt de cadeautjes in je schoen? Sinterklaas of de Kerstman?", answer: "Sinterklaas" },
  { id: 251, type: "SINTERKERSTMAN", difficulty: "easy", text: "Wie legt de cadeautjes onder een boom? Sinterklaas of de Kerstman?", answer: "De Kerstman" },
  { id: 252, type: "SINTERKERSTMAN", difficulty: "easy", text: "Wie draagt er rode kleding? Sinterklaas of de Kerstman?", answer: "Allebei" },
  { id: 253, type: "SINTERKERSTMAN", difficulty: "easy", text: "Wie heeft een gouden staf in zijn hand? Sinterklaas of de Kerstman?", answer: "Sinterklaas" },
  { id: 254, type: "SINTERKERSTMAN", difficulty: "easy", text: "Wie draagt een slappe muts met een wit bolletje eraan? Sinterklaas of de Kerstman?", answer: "De Kerstman" },
  { id: 255, type: "SINTERKERSTMAN", difficulty: "easy", text: "Wie gaat er door de schoorsteen om binnen te komen? Sinterklaas of de Kerstman?", answer: "Allebei (Ze doen het allebei!)" }
];


// ES6 Export
export { VRAGEN };
